#!/bin/sh
dir="$(dirname "$0")"

if [ "$#" -lt 2 ]; then
    echo 'Usage: idman GIT_REPO_FOLDER ALGORITHM [ARGS...]' 1>&2
    exit 1
fi

repo="$1"
shift

algorithm=$1
shift
if [ ! -e "$dir/graph/${algorithm}.py" ]; then
    echo "No such algorithm: '$algorithm'" 1>&2
    exit 2
fi

"$dir/parseman" "$repo" | "$dir/graph/graphman" "$algorithm" "$@"
