#!/bin/sh
dir="$(dirname "$0")"

if [ "$#" -lt 2 ]; then
    echo 'Usage: idman GIT_REPO_FOLDER BACKEND [BACKEND_ARGS...]' 1>&2
    exit 1
fi

repo="$1"
shift

backend=$1
shift
if [ ! -e "$dir/$backend" ]; then
    echo "No such backend: '$backend'" 1>&2
    exit 2
fi

"$dir/parseman" "$repo" | "$dir/$backend" "$@"
