#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename qw(dirname);
use lib dirname(__FILE__);
use Graph::Man;

my $algorithm  = ucfirst lc shift @ARGV;
print Graph::Man::identify(\*STDIN, $algorithm, @ARGV), "\n";
