#!/usr/bin/env perl
use 5.016;
use warnings;
use File::Basename qw(dirname);
use lib dirname(__FILE__);
use Graph::Man;

say Graph::Man::identify(\*STDIN, @ARGV);

__END__

=head1 NAME

graphman - merge identities by connecting graph nodes

=head1 SYNOPSIS

    parseman GIT_REPO_FOLDER | graphman GIT_REPO_FOLDER [ALGORITHM [ARGS...]]

=cut
