#!/usr/bin/env perl
use strict;
use warnings;
use autodie ':all';
use File::Basename qw(basename);

my @ALGORITHMS = (
    'default',
    'occurrence',
    'similarity',
    'bird',
);

mkdir 'results' if not -d 'results';
$ENV{GRAPHMAN_THRESHOLD} = 0.9;

for my $algorithm (@ALGORITHMS) {
    my $dir = "results/$algorithm";
    mkdir $dir if not -d $dir;

    for my $repo (glob 'repos/*') {
        my $base = basename($repo);
        print "$algorithm\t$base\n";
        system "../../idman $repo $algorithm > '$dir/$base.json'";
    }
}
