#!/usr/bin/perl
use strict;
use warnings;
use autodie ':all';
use File::Basename qw(basename);
use JSON::PP;
use Path::Tiny;

mkdir 'charts' if not -d 'charts';

for (glob 'output/default/*.json') {
    my $name = basename($_) =~ s/\.json$//r;
    my $json = decode_json(path($_)->slurp);

    {
        my @csv  = join "\n", map { "\u$_,$json->{$_}" } qw(authors committers both);
        open my $fh, '>:encoding(UTF-8)', "charts/$name-authors.csv";
        print {$fh} "@csv\n";
        close $fh;
    }

    {
        my @csv  = join "\n", map { "\u$_,$json->{$_}" } qw(same different);
        open my $fh, '>:encoding(UTF-8)', "charts/$name-commits.csv";
        print {$fh} "@csv\n";
        close $fh;
    }
}
